// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    01_basicGrammar: typeof import('./src/components/01_basic-grammar.vue')['default']
    01_basicGrammer: typeof import('./src/components/01_basic-grammer.vue')['default']
    02_component: typeof import('./src/components/02_component.vue')['default']
    02_componentValueTransfer: typeof import('./src/components/02_component-value-transfer.vue')['default']
    03_registerComponent: typeof import('./src/components/03_register-component.vue')['default']
    04_useScss: typeof import('./src/components/04_use-scss.vue')['default']
    05_dynamicComponent: typeof import('./src/components/05_dynamic-component.vue')['default']
    2: typeof import('./src/components/cpns/dynamic-a copy 2.vue')['default']
    copy: typeof import('./src/components/cpns/dynamic-a copy.vue')['default']
    DynamicA: typeof import('./src/components/cpns/dynamic-a.vue')['default']
    DynamicB: typeof import('./src/components/cpns/dynamic-b.vue')['default']
    DynamicC: typeof import('./src/components/cpns/dynamic-c.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    GlobalComponent: typeof import('./src/components/cpns/global-component.vue')['default']
    GlobComponent: typeof import('./src/components/cpns/glob-component.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/cpns/menu.vue')['default']
    Tree: typeof import('./src/components/cpns/tree.vue')['default']
  }
}
