// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    01_basicGrammar: typeof import('./src/components/01_basic-grammar.vue')['default']
    01_basicGrammer: typeof import('./src/components/01_basic-grammer.vue')['default']
    02_component: typeof import('./src/components/02_component.vue')['default']
    02_componentValueTransfer: typeof import('./src/components/02_component-value-transfer.vue')['default']
    03_registerComponent: typeof import('./src/components/03_register-component.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Menu: typeof import('./src/components/cpns/menu.vue')['default']
  }
}
